# Generated by Django 6.0.7 on 2026-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('accommodation', 'Safari Accommodation'), ('game_drives', 'Game Drives'), ('camping', 'Camping Equipment'), ('photography', 'Photography Equipment'), ('hunting', 'Hunting Equipment'), ('drones', 'Monitoring Drones')], max_length=50),
        ),
    ]
